// <auto-generated />
using System;
using AcademiaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademiaAPI.Migrations
{
    [DbContext(typeof(AcademiaContext))]
    partial class AcademiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AcademiaAPI.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            IdAluno = 1,
                            Ativo = true,
                            CPF = "111.222.333-44",
                            DataNascimento = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana@email.com",
                            Nome = "Ana Paula",
                            Telefone = "14999990001"
                        },
                        new
                        {
                            IdAluno = 2,
                            Ativo = true,
                            CPF = "555.666.777-88",
                            DataNascimento = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bruno@email.com",
                            Nome = "Bruno Costa",
                            Telefone = "14999990002"
                        });
                });

            modelBuilder.Entity("AcademiaAPI.Models.InscricaoTurma", b =>
                {
                    b.Property<int>("IdInscricao_turma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAluno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTurma")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdInscricao_turma");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdTurma");

                    b.ToTable("InscricoesTurma");

                    b.HasData(
                        new
                        {
                            IdInscricao_turma = 1,
                            Ativo = true,
                            DataInscricao = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAluno = 1,
                            IdTurma = 1
                        },
                        new
                        {
                            IdInscricao_turma = 2,
                            Ativo = true,
                            DataInscricao = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAluno = 2,
                            IdTurma = 2
                        });
                });

            modelBuilder.Entity("AcademiaAPI.Models.Instrutor", b =>
                {
                    b.Property<int>("IdInstrutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CREF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdInstrutor");

                    b.ToTable("Instrutores");

                    b.HasData(
                        new
                        {
                            IdInstrutor = 1,
                            Ativo = true,
                            CREF = "012345-G/SP",
                            DataContratacao = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos@academia.com",
                            Especialidade = "Musculação",
                            Nome = "Carlos Souza"
                        },
                        new
                        {
                            IdInstrutor = 2,
                            Ativo = true,
                            CREF = "067890-G/SP",
                            DataContratacao = new DateTime(2021, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernanda@academia.com",
                            Especialidade = "Yoga",
                            Nome = "Fernanda Lima"
                        });
                });

            modelBuilder.Entity("AcademiaAPI.Models.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAluno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPlano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdMatricula");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdPlano");

                    b.ToTable("Matriculas");

                    b.HasData(
                        new
                        {
                            IdMatricula = 1,
                            DataFim = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAluno = 1,
                            IdPlano = 2,
                            Situacao = "Ativa",
                            ValorPago = 139.90m
                        },
                        new
                        {
                            IdMatricula = 2,
                            DataFim = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAluno = 2,
                            IdPlano = 1,
                            Situacao = "Ativa",
                            ValorPago = 89.90m
                        });
                });

            modelBuilder.Entity("AcademiaAPI.Models.Plano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracaoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncluiAcompanhamentoNutricional")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncluiAulasColetivas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomePlano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorMensalidade")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPlano");

                    b.ToTable("Planos");

                    b.HasData(
                        new
                        {
                            IdPlano = 1,
                            Ativo = true,
                            DuracaoMeses = 1,
                            IncluiAcompanhamentoNutricional = false,
                            IncluiAulasColetivas = false,
                            NomePlano = "Básico",
                            ValorMensalidade = 89.90m
                        },
                        new
                        {
                            IdPlano = 2,
                            Ativo = true,
                            DuracaoMeses = 1,
                            IncluiAcompanhamentoNutricional = false,
                            IncluiAulasColetivas = true,
                            NomePlano = "Premium",
                            ValorMensalidade = 139.90m
                        },
                        new
                        {
                            IdPlano = 3,
                            Ativo = true,
                            DuracaoMeses = 1,
                            IncluiAcompanhamentoNutricional = true,
                            IncluiAulasColetivas = true,
                            NomePlano = "VIP",
                            ValorMensalidade = 249.90m
                        });
                });

            modelBuilder.Entity("AcademiaAPI.Models.Turma", b =>
                {
                    b.Property<int>("IdTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdInstrutor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTurma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTurma");

                    b.HasIndex("IdInstrutor");

                    b.ToTable("Turmas");

                    b.HasData(
                        new
                        {
                            IdTurma = 1,
                            CapacidadeMaxima = 30,
                            DiaSemana = "Segunda",
                            Horario = new TimeOnly(7, 0, 0),
                            IdInstrutor = 1,
                            Modalidade = "Musculação",
                            NomeTurma = "Musculação Manhã"
                        },
                        new
                        {
                            IdTurma = 2,
                            CapacidadeMaxima = 20,
                            DiaSemana = "Quarta",
                            Horario = new TimeOnly(14, 0, 0),
                            IdInstrutor = 2,
                            Modalidade = "Yoga",
                            NomeTurma = "Yoga Tarde"
                        });
                });

            modelBuilder.Entity("AcademiaAPI.Models.InscricaoTurma", b =>
                {
                    b.HasOne("AcademiaAPI.Models.Aluno", "Aluno")
                        .WithMany("InscricoesTurma")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaAPI.Models.Turma", "Turma")
                        .WithMany("InscricoesTurma")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Matricula", b =>
                {
                    b.HasOne("AcademiaAPI.Models.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaAPI.Models.Plano", "Plano")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Turma", b =>
                {
                    b.HasOne("AcademiaAPI.Models.Instrutor", "Instrutor")
                        .WithMany("Turmas")
                        .HasForeignKey("IdInstrutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrutor");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Aluno", b =>
                {
                    b.Navigation("InscricoesTurma");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Instrutor", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Plano", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("AcademiaAPI.Models.Turma", b =>
                {
                    b.Navigation("InscricoesTurma");
                });
#pragma warning restore 612, 618
        }
    }
}
